controller_list:
  - name: fake_yaskawa_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_s
      - joint_l
      - joint_e
      - joint_u
      - joint_r
      - joint_b
      - joint_t
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - right_joint
initial:  # Define initial robot poses per group
  - group: yaskawa_arm
    pose: zero